# Generated by Django 5.1.3 on 2024-11-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='tipo',
            field=models.CharField(choices=[('examen', 'Examen'), ('inicio_semestre', 'Inicio de Semestre'), ('fin_semestre', 'Fin de Semestre'), ('receso', 'Receso Académico'), ('otro', 'Otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
